channels:
- conda-forge
dependencies:
- python=3.10.9
- pip<=22.3.1
- pip:
  - mlflow<3,>=2.1
  - cloudpickle==2.0.0
  - psutil==5.9.0
  - scikit-learn==1.1.3
  - typing-extensions==4.4.0
  - xgboost==1.5.0
name: mlflow-env
